[package]
name = "rust_compressor"
version = "0.1.6"

[dependencies]
polytype = "4.2"
programinduction = { version = "0.6.9" , features = [ "verbose" ] }
rayon = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
