[package]
name = "rust_compressor"
version = "0.1.9"

[dependencies]
polytype = "5.0"
programinduction = { version = "0.6.12" , features = [ "verbose" ] }
rayon = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
